# IP Piso
@api = http://192.168.1.136:3000

# IP Bt3
# @api = http://192.168.10.29:3000 


POST {{api}}/articles
Content-Type: application/json

{
    "title":"desde articles.http",
    "body":"el cuerpo"
}

###
GET {{api}}/articles

###
GET {{api}}/articles/3

###
PUT {{api}}/articles/5
Content-Type: application/json

{
    "title":"updated desde articles.http",
    "body":"el cuerpo updated"
}

###
DELETE {{api}}/articles/15

###
GET {{api}}/api/docs

###
GET {{api}}/articles/count

###
GET {{api}}/articles/get-by-title/28